In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print("DataType : ",a.dtype)
print(a.ndim)
print(a.shape)
print(len(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>
DataType int32
1
(5,)
5


In [3]:
import numpy as np
myList=[[1,2,3],[4,5,6],[7,8,9]]
np.array(myList)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.random.rand(5)


array([0.13348488, 0.88369116, 0.58456733, 0.33089446, 0.38780712])

In [5]:
np.random.rand(4,4)

array([[0.71209302, 0.53797939, 0.28704795, 0.12031819],
       [0.23545597, 0.28420785, 0.24547432, 0.47248114],
       [0.29152646, 0.67503295, 0.27997988, 0.98474311],
       [0.46346538, 0.61845317, 0.06755011, 0.43913725]])

In [7]:
np.random.randn(4)

array([-1.37979673,  1.23690276,  1.00370208, -0.11403075])

In [8]:
import numpy as np
energy_consumption=np.array([1200,3400,2900,1800,2500])
print("Energy Consumption (in MWH) for Different Renewable Sourse : ")
print(energy_consumption)

Energy Consumption (in MWH) for Different Renewable Sourse : 
[1200 3400 2900 1800 2500]
